import { prefix, prefix2 } from './UrlsConfig';
import { base_config } from '../../main/consts/BaseData';

const basic = 'basic';

// const BaseDataUrls = {
//     BASEDATA:base_config.map((item)=>{
//         let list = item.tableData ? item.tableData : item.e_name;
//         return {
//             getList:`${prefix}/${basic}/${list}/getList`,
//             getDetail: `${prefix}/${basic}/${item.e_name}/getDetail`,
//             delete: `${prefix}/${basic}/${item.e_name}/delete`,
//             add: `${prefix}/${basic}/${item.e_name}/add`,
//             updata: `${prefix}/${basic}/${item.e_name}/updata`,
//         }
//     })
// }
const BaseDataUrls = {
    BASEDATA: [{
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }, {
        getList: `${prefix}/${basic}/country/getList`,
        getDetail: `${prefix}/${basic}/country/getDetail`,
        delete: `${prefix}/${basic}/country/delete`,
        add: `${prefix}/${basic}/country/add`,
        updata: `${prefix}/${basic}/country/updata`,
    }],
};

export default BaseDataUrls;